### ISSUE TITLE
docker compose fails on poetry

### ISSUE THREAD

**Issue by elikling** [microsoft/showwhy#319]
At long last I have manage to figure out how to get 'docker-compose --profile all up' to work on Azure VMs.
On an Ubuntu there is some stuff that needs to be installed and the syntax is 'docke compose --profile all up' [no hypen after the docer].

So on Unix the docker copose call downloads everything and seems to work 
![image](https://user-images.githubusercontent.com/8556526/204906590-ae608d20-f9d0-4f13-bdd6-ef3cbe4812c5.png)

but for a Windows 11 azure VM I get an error message

#18 [showwhy-backend_worker 11/12] RUN poetry config virtualenvs.create false     && ./scripts/install_python_deps.sh
#18 1.223 /bin/sh: 1: ./scripts/install_python_deps.sh: not found
#18 ERROR: executor failed running [/bin/sh -c poetry config virtualenvs.create false     && ./scripts/install_python_deps.sh]: exit code: 127
------
 > [showwhy-backend_worker 11/12] RUN poetry config virtualenvs.create false     && ./scripts/install_python_deps.sh:
#18 1.223 /bin/sh: 1: ./scripts/install_python_deps.sh: not found
------
failed

**Comment by rracanicci** [comment]
Hello @elikling, thank you very much for your feedback.

This issue is related to line endings on Windows and should have been resolved by this [PR](https://github.com/microsoft/showwhy/pull/334). It updates the git attributes file to keep the `LF` end of lines in the `.sh` scripts when project is cloned.

You can either clone the project again or locally update the `.sh` scripts to use `LF` instead of `CRLF` as line endings.
