### ISSUE TITLE
Data Import Limitations? / Information on Data Import

### ISSUE THREAD

**Issue by hrbrill** [microsoft/showwhy#391]
We've experienced crashes when importing large CSV data files into ShowWhy. (We have been successful with smaller files.) Are there known limits to the size of files that can be imported? (We are currently testing files of different sizes.) 

Also, is there documentation on the file import process? The readme.md file does not detail the process or its limitations.

From the in-application dialogs, it appears that only CSV and JSON files are supported. I'm curious whether other formats such as Parquet may be supported.

**Comment by dayesouza** [comment]
Hi @hrbrill! If I'm not mistaken the browser gets stuck with large files, and we would need to upload large files into chunks.

About CSV and JSON import, we're using only the default formats that [Arquero](https://uwdata.github.io/arquero/) supports, since we're using this library to load and format the data.

I'll be adding the large files suggestion into our board, but contributions are welcome if you want to 😄
